[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "glcp-nnunet"
version = "0.0.0"
description = "GLCP fork additions for nnUNetv2"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["nnunetv2"]
